apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-f4i0
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0012-tenant/tkrw-pr712-0075-0012-app/devfile-sample-f4i0@sha256:76eceabbe4d6c56f899540ea49825258affb0244210ab8eac685b4b5945f81ed
        name: my-nodejs
        resources: {}
status: {}
